[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = false
optimizer = true
optimizer_runs = 10000
ignored_warnings = ["2018"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
